### ISSUE TITLE
SimpleLogin domains included in your disposable emails list 

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [sublime-security/static-files#103]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that some of our domains are present your list of disposable emails. 

To be more precise, dralias.com, 8alias.com, slmail.me, aleeas.com, simplelogin.fr, and 8shield.net, are included. Could we trouble you to clarify why this is the case and whether it would be possible to correct it?

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by morriscode** [comment]
@Nikola-Test-for-Proton  & @Timmi5853  Thank you both for reaching out. I will look into this tomorrow and adjust accordingly!

**Comment by morriscode** [comment]
Thank you both, the associated [PR](https://github.com/sublime-security/static-files/pull/133) has been consumed!
