### ISSUE TITLE
Add new disposable

### ISSUE THREAD

**Issue by ghost** [sublime-security/static-files#149]
```
mailbox.zip
sailmail.io
```

See https://github.com/sublime-security/static-files/issues/137

They just added new domains:
![IMG_1719](https://github.com/sublime-security/static-files/assets/155534304/bc542c77-ba36-4c1a-a7cf-3d15b8c7dfc0)

**Comment by Fhciv** [comment]
@morriscode

**Comment by morriscode** [comment]
many thanks!! PR submitted for approval
